version: '3.7'

services:
  web:
    build: 
      context: ../app
      dockerfile: Dockerfile.prod
    image: portfolio-prod:1.0.0
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file: ../env/prod.env
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ../env/prod_db.env
  nginx:
    build: ../nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 1400:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
